name: shu

on:
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * *'

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run download script
        run: python shu.py

      - name: Upload downloaded file
        uses: actions/upload-artifact@v3
        with:
          name: downloaded_content
          path: Scripts/shu

      - name: Commit 和 push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .

          # 检查是否有文件被修改
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "ke"
            git push
          fi
